<Circle>:
    canvas:
        Color:
            hsv: 0,0,self.v
        Ellipse:
            pos: self.pos
            size: self.size

<Illusion>:
    c1: _c1
    c2: _c2
    c3: _c3
    c4: _c4

    Circle:
        id: _c1
        size: 250,250
        center_x: self.parent.width / 4
        center_y: self.parent.height / 2

    Circle:
        id: _c2
        size: 250,250
        center_x: self.parent.width * 3/4
        center_y: self.parent.height / 2

    Circle:
        id: _c3
        size: 180,180
        center_x: self.parent.width / 4
        center_y: self.parent.height / 2

    Circle:
        size: 180,180
        id: _c4
        center_x: self.parent.width * 3/4
        center_y: self.parent.height / 2